name: Flask CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Create and activate virtual environment
        run: |
          cd flask-madlibs
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd flask-madlibs
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Run Flask application
        run: |
          cd flask-madlibs
          python app.py
